# Generated by Django 3.1.1 on 2020-09-22 18:05

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('ph_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Phone Number')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('profile_pic', models.ImageField(default='user/user.png', upload_to='user/', verbose_name='Profile Picture')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Gender')),
                ('account_type', models.CharField(blank=True, choices=[('BUSINESS', 'Business'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=8, verbose_name='Account Type')),
                ('website', models.URLField(blank=True, max_length=75, verbose_name='Website')),
                ('show_activity_status', models.BooleanField(default=True)),
                ('allow_sharing', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='Follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='Following', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
